### ISSUE TITLE
'merge files' button not triggering any action

### ISSUE THREAD

**Issue by gbinal** [kinlane/data-json-file-merger#1]
Kin, this is great.  

Just starting to play with it but one thing is that I'm not able to complete the activity because the Merge Files button isn't working for me.  I successfully load 2 different json files and try to click Merge Files but nothing happens.  Add Another File works well, though.  

Using Chrome on a Windows 7 machine, but fwiw, I definitely might be missing something.

**Comment by kinlane** [comment]
Hmmm....could you send me the 2 json files you are trying load? I'll debug.

**Comment by gbinal** [comment]
Sure enough - this was a result of poor formatting in my json files.  After correcting my json and trying again, the tool worked well.
